create database biblioteca;
use bibliioteca;
CREATE TABLE libros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    año_publicacion INT NOT NULL,  
    genero VARCHAR(100) NOT NULL
);

INSERT INTO libros (titulo, autor, año_publicacion, genero) VALUES
('Cien años de soledad', 'Gabriel García Márquez', 1967, 'Ficción'),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'Ficción'),
('El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 'Ficción'),
('La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Ficción'),
('1984', 'George Orwell', 1949, 'Distopía'),
('Orgullo y prejuicio', 'Jane Austen', 1813, 'Romance'),
('Moby Dick', 'Herman Melville', 1851, 'Aventura'),
('El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Ficción'),
('Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 'Ficción'),
('El túnel', 'Ernesto Sabato', 1948, 'Ficción'),
('Fahrenheit 451', 'Ray Bradbury', 1953, 'Ciencia ficción'),
('El viejo y el mar', 'Ernest Hemingway', 1952, 'Ficción'),
('Cumbres borrascosas', 'Emily Brontë', 1847, 'Ficción'),
('El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'Ficción'),
('Los miserables', 'Victor Hugo', 1862, 'Ficción'),
('La casa de los espíritus', 'Isabel Allende', 1982, 'Ficción'),
('El principito', 'Antoine de Saint-Exupéry', 1943, 'Ficción'),
('Rayuela', 'Julio Cortázar', 1963, 'Ficción'),
('El alquimista', 'Paulo Coelho', 1988, 'Ficción'),
('La tregua', 'Mario Benedetti', 1960, 'Ficción'),
('El proceso', 'Franz Kafka', 1925, 'Ficción'),
('El guardián entre el centeno', 'J.D. Salinger', 1951, 'Ficción'),
('En busca del tiempo perdido', 'Marcel Proust', 1913, 'Ficción'),
('Las aventuras de Tom Sawyer', 'Mark Twain', 1876, 'Aventura'),
('El conde de Montecristo', 'Alexandre Dumas', 1844, 'Aventura'),
('El diario de Ana Frank', 'Ana Frank', 1947, 'No ficción'),
('La odisea', 'Homero', -800, 'Épico'),
('El arte de la guerra', 'Sun Tzu', -500, 'No ficción'),
('Siddhartha', 'Hermann Hesse', 1922, 'Ficción'),
('El juego del ángel', 'Carlos Ruiz Zafón', 2008, 'Ficción'),
('Los ojos del perro siberiano', 'Antonio Garrido', 1999, 'Ficción'),
('El hombre en busca de sentido', 'Viktor Frankl', 1946, 'No ficción'),
('La historia interminable', 'Michael Ende', 1979, 'Fantasía'),
('Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Fantasía'),
('El hobbit', 'J.R.R. Tolkien', 1937, 'Fantasía'),
('Cazadores de sombras', 'Cassandra Clare', 2007, 'Fantasía'),
('El nombre del viento', 'Patrick Rothfuss', 2007, 'Fantasía'),
('La chica del tren', 'Paula Hawkins', 2015, 'Thriller'),
('El silencio de los corderos', 'Thomas Harris', 1988, 'Thriller'),
('La chica que soñaba con una cerilla y un bidón de gasolina', 'Stieg Larsson', 2006, 'Thriller'),
('El psicoanalista', 'John Katzenbach', 2002, 'Thriller'),
('El código Da Vinci', 'Dan Brown', 2003, 'Thriller'),
('La verdad sobre el caso Harry Quebert', 'Joël Dicker', 2012, 'Thriller'),
('Los hombres que no amaban a las mujeres', 'Stieg Larsson', 2005, 'Thriller'),
('El secreto', 'Rhonda Byrne', 2006, 'Autoayuda'),
('Cómo ganar amigos e influir sobre las personas', 'Dale Carnegie', 1936, 'Autoayuda'),
('Piense y hágase rico', 'Napoleon Hill', 1937, 'Autoayuda'),
('Los 7 hábitos de la gente altamente efectiva', 'Stephen Covey', 1989, 'Autoayuda'),
('Despierta tu héroe interior', 'Victor Hugo Manzanilla', 2018, 'Autoayuda');